name: Gatsby build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
